apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.8.75
    helm:
      values: |
        controller:
          serviceType: ClusterIP
          admin:
            password: admin
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
            hostName: jenkins.localhost
            path: /
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
